export const CHANGE_WORK_INFO = 'CHANGE_WORK_INFO'
export const CHANGE_USER_INFO = 'CHANGE_USER_INFO'
export const CHANGE_COMPANY_INFO = 'CHANGE_COMPANY_INFO'

export const CHANGE_FORM = 'CHANGE_FORM'
export const CHANGE_CHOOSEDTD = 'CHANGE_CHOOSEDTD'